language: ruby
rvm:
- 2.0.0
env:
  global:
    secure: ereauGEcswkTAMSZqXiHx1nuqz/LOBO8uLNBml/UUxoYa8siN4ZlNUZkHk631sbEbqIPjNVb6jcOBVLkiDeEDl3HFkmZrOpL4gNnvsoFYYL4ZnXgfytIa7/y4MOcwXQ/HO7L3Z1WWspC3lxWgJjtIKiAzOVz2gsCMRRJ2WhAZ4A=
